/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.table.DefaultTableModel;
import Clases.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author oscar
 */
public class MenuAccionesDispositivos extends javax.swing.JDialog {

    /**
     * Creates new form MenuAccionesDispositivos
     */
    public MenuAccionesDispositivos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        ActualizarTabla();
    }
    public ListaEnlazada lista = new ListaEnlazada();

    MenuAccionesDispositivos() {
       
    }

    public void setLista(ListaEnlazada lista) {
        this.lista = lista;
    }

    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        Dispositivos = new javax.swing.JMenu();
        GestionarDispositivos = new javax.swing.JMenuItem();
        Acciones = new javax.swing.JMenu();
        AccionesDispositivos = new javax.swing.JMenuItem();
        AccionesExternas = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        Bitácora = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel1.setText("Acciones con Dispositivos");

        tblDatos = new JTable(){
            public boolean isCellEditable(int row, int column){
                for(int i = 0; i < tblDatos.getRowCount(); i++){
                    if(row == i){
                        return false;
                    }
                }
                return true;
            }
        };
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        Dispositivos.setText("Dispositivos");

        GestionarDispositivos.setText("Gestionar Dispositivos");
        GestionarDispositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarDispositivosActionPerformed(evt);
            }
        });
        Dispositivos.add(GestionarDispositivos);

        jMenuBar1.add(Dispositivos);

        Acciones.setText("Acciones");

        AccionesDispositivos.setText("Acciones con Dispositivos");
        AccionesDispositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionesDispositivosActionPerformed(evt);
            }
        });
        Acciones.add(AccionesDispositivos);

        AccionesExternas.setText("Acciones Externas al Dispositivo");
        AccionesExternas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionesExternasActionPerformed(evt);
            }
        });
        Acciones.add(AccionesExternas);

        jMenuBar1.add(Acciones);

        Reportes.setText("Reportes");

        Bitácora.setText("Bitácora");
        Bitácora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BitácoraActionPerformed(evt);
            }
        });
        Reportes.add(Bitácora);

        jMenuBar1.add(Reportes);

        jMenu1.setText("Usuarios");

        jMenuItem1.setText("Gestionar Usuarios");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static String dato;
    
    public void ActualizarTabla() {
        this.lista = lista;
        Nodo temporal;
        temporal = lista.head;
        String sql = "SELECT * FROM DISPOSITIVO";

        modelo.addColumn("identificador");
        modelo.addColumn("Tipo");
        modelo.addColumn("Nombre");

        Dispositivos dispositivo = new Dispositivos();
        //if (temporal != (null)) {
        Interfaz acceso = new Interfaz();
        String[] arreglo = new String[3];
        try {
            Connection conn = ConexionDB.getConexionDB(acceso.usuario1, acceso.contraseña1).getConn();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                //CORREO, NOMBRE, TIPO, CONEXION, VISIBLE,ENCENDIDO, NUMERO
                dispositivo.setCorreoElectronico(rs.getString(2));
                dispositivo.setNumero(rs.getString(3));
                dispositivo.setConexion(rs.getString(4));
                dispositivo.setVisible(rs.getString(5));
                dispositivo.setEncendido(rs.getString(6));
                dispositivo.setNumero(rs.getString(7));

                this.lista.insertarFinal(dispositivo);

                arreglo[0] = rs.getString(1);
                arreglo[1] = rs.getString(4);
                arreglo[2] = rs.getString(3);

                modelo.addRow(arreglo);

                if (tblDatos.getModel().getRowCount() == 0) {
                    System.out.println("no se encontro ninguna concidencia");

                }
                tblDatos.setModel(modelo);
            }
            
             AccionesDispositivos a = new AccionesDispositivos();
            a.setLista(lista);

        } catch (SQLException ex) {
            System.out.println(ex);
            // Logger.getLogger(sql).log(Level.SERVERE,null,ex);
        }

        //}
    }
    private void GestionarDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarDispositivosActionPerformed
        this.setVisible(false);
        Interfaz interfaz = new Interfaz();
        new GestionarDispositivos(interfaz,true).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GestionarDispositivosActionPerformed
 
    private void AccionesExternasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionesExternasActionPerformed
      this.setVisible(false);
        Interfaz interfaz = new Interfaz();
        new AccionesExternas(interfaz,true).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AccionesExternasActionPerformed

    private void BitácoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BitácoraActionPerformed
       this.setVisible(false);
        Interfaz interfaz = new Interfaz();
        new Bitácora (interfaz,true).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BitácoraActionPerformed

    private void AccionesDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionesDispositivosActionPerformed
        this.setVisible(false);
        Interfaz interfaz = new Interfaz();
        new AccionesDispositivos(interfaz,true).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AccionesDispositivosActionPerformed

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
         if (evt.getClickCount() == 2) {
            DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
            int fila = tblDatos.getSelectedRow();

            if (fila >= 0) {
                this.dato = String.valueOf(modelo.getValueAt(tblDatos.getSelectedRow(), 0));
                this.setVisible(false);
                Interfaz interfaz = new Interfaz();
                new AccionesDispositivos(interfaz, true).setVisible(true);
                this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un Dispositivo");
            }
        }
    }//GEN-LAST:event_tblDatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAccionesDispositivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAccionesDispositivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAccionesDispositivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAccionesDispositivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuAccionesDispositivos dialog = new MenuAccionesDispositivos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acciones;
    private javax.swing.JMenuItem AccionesDispositivos;
    private javax.swing.JMenuItem AccionesExternas;
    private javax.swing.JMenuItem Bitácora;
    private javax.swing.JMenu Dispositivos;
    private javax.swing.JMenuItem GestionarDispositivos;
    private javax.swing.JMenu Reportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables

    private AccionesExternas AccionesExternas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private AccionesDispositivos AccionesDispositivos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
