
package Ventanas;

import Clases.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar
 */
public class Usuarios extends javax.swing.JDialog {

    /**
     * Creates new form Usuarios
     */
    public Usuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        ActualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Crear = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Dispositivos = new javax.swing.JMenu();
        GestionarDispositivos = new javax.swing.JMenuItem();
        Acciones = new javax.swing.JMenu();
        AccionesDispositivos = new javax.swing.JMenuItem();
        AccionesExternas = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        Bitácora = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setText("Gestionar usuarios");

        Tabla = new JTable(){
            public boolean isCellEditable(int row, int column){
                for(int i = 0; i < Tabla.getRowCount(); i++){
                    if(row == i){
                        return false;
                    }
                }
                return true;
            }
        };
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        Crear.setText("Crear usuario");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar usuario");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Dispositivos.setText("Dispositivos");

        GestionarDispositivos.setText("Gestionar Dispositivos");
        GestionarDispositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarDispositivosActionPerformed(evt);
            }
        });
        Dispositivos.add(GestionarDispositivos);

        jMenuBar1.add(Dispositivos);

        Acciones.setText("Acciones");

        AccionesDispositivos.setText("Acciones con Dispositivos");
        AccionesDispositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionesDispositivosActionPerformed(evt);
            }
        });
        Acciones.add(AccionesDispositivos);

        AccionesExternas.setText("Acciones Externas al Dispositivo");
        AccionesExternas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionesExternasActionPerformed(evt);
            }
        });
        Acciones.add(AccionesExternas);

        jMenuBar1.add(Acciones);

        Reportes.setText("Reportes");

        Bitácora.setText("Bitácora");
        Bitácora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BitácoraActionPerformed(evt);
            }
        });
        Reportes.add(Bitácora);

        jMenuBar1.add(Reportes);

        jMenu1.setText("Usuarios");

        jMenuItem1.setText("Gestionar Usuarios");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(Crear)
                        .addGap(100, 100, 100)
                        .addComponent(Eliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Crear)
                    .addComponent(Eliminar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static String dato;
    DefaultTableModel modelo = new DefaultTableModel();
   public ListaEnlazada lista = new ListaEnlazada();   
    
    public void ActualizarTabla() {
        int y = 0;
       

        String sql = "SELECT * FROM admin.USUARIOS";

        modelo.addColumn("Identificador");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Correo Electronico");
        modelo.addColumn("Contraseña");

        Interfaz acceso = new Interfaz();
        String[] arreglo = new String[5];
        try {
            Connection conn = ConexionDB.getConexionDB(acceso.usuario1, acceso.contraseña1).getConn();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
Usuario usuario = new Usuario();

            while (rs.next()) {
                usuario.setId(rs.getString(1));
                usuario.setNombre(rs.getString(2));
                usuario.setApellido(rs.getString(3));
                usuario.setCorreo(rs.getString(4));
                usuario.setContraseña(rs.getString(5));
                
                lista.insertarFinal(usuario);
                 
                
                arreglo[0] = rs.getString(1);
                arreglo[1] = rs.getString(2);
                arreglo[2] = rs.getString(3);
                arreglo[3] = rs.getString(4);
                arreglo[4] = rs.getString(5);

                modelo.addRow(arreglo);
                // lista.tail.setSiguiente();arreglo[0]      agregar a la lista enlazada los nuevos

                
                Tabla.setModel(modelo);
                y++;

            }

        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }
    private void GestionarDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarDispositivosActionPerformed
        this.setVisible(false);
        Interfaz interfaz = new Interfaz();
        new GestionarDispositivos(interfaz, true).setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_GestionarDispositivosActionPerformed

    private void AccionesDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionesDispositivosActionPerformed
        this.setVisible(false);
        Interfaz interfaz = new Interfaz();
        new MenuAccionesDispositivos(interfaz, true).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AccionesDispositivosActionPerformed

    private void AccionesExternasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionesExternasActionPerformed
        this.setVisible(false);
        Interfaz interfaz = new Interfaz();
        new AccionesExternas(interfaz, true).setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_AccionesExternasActionPerformed

    private void BitácoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BitácoraActionPerformed
        this.setVisible(false);
        Interfaz interfaz = new Interfaz();
        new Bitácora(interfaz, true).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BitácoraActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        this.setVisible(false);
        Interfaz interfaz = new Interfaz();
        new CrearUsuario(interfaz, true).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CrearActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
        int fila = Tabla.getSelectedRow();

        if (fila >= 0) {
            dato = String.valueOf(modelo.getValueAt(Tabla.getSelectedRow(), 0));
            modelo.removeRow(fila);
            try {
                UsuariosDB.eliminar(dato);
            } catch (SQLException ex) {
                Logger.getLogger(GestionarDispositivos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un Dispositivo");
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        if (evt.getClickCount() == 2) {
            DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
            int fila = Tabla.getSelectedRow();

            if (fila >= 0) {
                this.dato = String.valueOf(modelo.getValueAt(Tabla.getSelectedRow(), 0));

                this.setVisible(false);
                Interfaz interfaz = new Interfaz();
                new ModificarUsuario(interfaz, true).setVisible(true);
                this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un Dispositivo");
            }
        }

    }//GEN-LAST:event_TablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Usuarios dialog = new Usuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acciones;
    private javax.swing.JMenuItem AccionesDispositivos;
    private javax.swing.JMenuItem AccionesExternas;
    private javax.swing.JMenuItem Bitácora;
    private javax.swing.JButton Crear;
    private javax.swing.JMenu Dispositivos;
    private javax.swing.JButton Eliminar;
    private javax.swing.JMenuItem GestionarDispositivos;
    private javax.swing.JMenu Reportes;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
